#!/usr/bin/env bash

target_file=$1

if [ ! -e "${target_file}" ]; then
    echo "'${target_file}' is not exist."
    exit 1
fi

if [[ ! ${target_file} =~ .+\.tex ]]; then
    echo "'${target_file}' is not tex file."
    exit 1
fi

non_extension_file=${target_file%\.tex}

# latexmk ${target_file}
platex "${target_file}"

if [ -e "${non_extension_file}.dvi" ]; then
    dvipdfmx "${non_extension_file}.dvi"
fi
wait

if [ -e "${non_extension_file}.aux" ]; then
    rm "${non_extension_file}.aux"
fi

if [ -e "${non_extension_file}.dvi" ]; then
    rm "${non_extension_file}.dvi"
fi

if [ -e "${non_extension_file}.fdb_latexmk" ]; then
    rm "${non_extension_file}.fdb_latexmk"
fi

if [ -e "${non_extension_file}.fls" ]; then
    rm "${non_extension_file}.fls"
fi

if [ -e "${non_extension_file}.log" ]; then
    rm "${non_extension_file}.log"
fi

if [ -e "${non_extension_file}.synctex.gz" ]; then
    rm "${non_extension_file}.synctex.gz"
fi

if [ -e "${non_extension_file}.nav" ]; then
    rm "${non_extension_file}.nav"
fi

if [ -e "${non_extension_file}.out" ]; then
    rm "${non_extension_file}.out"
fi

if [ -e "${non_extension_file}.snm" ]; then
    rm "${non_extension_file}.snm"
fi

if [ -e "${non_extension_file}.toc" ]; then
    rm "${non_extension_file}.toc"
fi

exit 0
